### ISSUE TITLE
RSVSim code for this project

### ISSUE THREAD

**Issue by xie186** [timoast/Arabidopsis-TE-variants#13]
Hi Stuart,

Can you kindly provide the R code you used for simulation of 100 TE insertion and 100 TE absence? 

Thanks,
Shaojun Xie

**Comment by timoast** [comment]
Hi Shaojun, please see my latest commit for all the code I used in simulating TE variation in Arabidopsis and for generating synthetic illumina reads

**Comment by readbio** [comment]
Thank you so much!

**Comment by xie186** [comment]
Thanks.
