### ISSUE TITLE
About discordant alignment

### ISSUE THREAD

**Issue by xie186** [timoast/Arabidopsis-TE-variants#14]
Hi Tim,
I didn't find an issue link for TEPID. So post this issue here for TEPID. 
I ran TEPID on PE reads. Sample name is WT. Then I got the following files:
```
WT.bam  WT.bam.bai  WT.split.bam  WT.umap.fastq
```
I didn't see discordant read mapping. But for tepid-discover, there is an argument: -D. Does this mean I need to extract discordant read mappings using samblaster before tepid-discover? 
Thanks,
Shaojun

**Comment by timoast** [comment]
Hi Shaojun, the `-D` argument is optional and was mainly used by me when developing TEPID to speed up testing of the code by skipping the discordant read finding step, so for your purpose I'd say don't use `-D`, tepid-discover will find the discordant read pairs for you

**Comment by xie186** [comment]
Got it. Thanks for your quick response.
